### ISSUE TITLE
00-envsubst-on-index.html.sh: not found

### ISSUE THREAD

**Issue by petermarcoen** [zaverden/frontend-env#2]
When I clone your repo and run docker-compose up --build as per the instructions the container immediately stops with an error. 

It complains about not finding 00-envsubst-on-index.html.sh, yet 1 line above it does find it. Or is something within that shell script not found?

```
web8080_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web8080_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
web8080_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/00-envsubst-on-index.html.sh
web8080_1  | /docker-entrypoint.sh: 22: /docker-entrypoint.sh: /docker-entrypoint.d/00-envsubst-on-index.html.sh: not found
web8081_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web8081_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
web8081_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/00-envsubst-on-index.html.sh
web8081_1  | /docker-entrypoint.sh: 22: /docker-entrypoint.sh: /docker-entrypoint.d/00-envsubst-on-index.html.sh: not found
frontend-env_web8080_1 exited with code 127
frontend-env_web8081_1 exited with code 127
```

**Comment by petermarcoen** [comment]
Nevermind, I found the problem.
Turns out that I had CRLF line endings in envsubst-on-index.html.sh instead of LF.

**Comment by zaverden** [comment]
@petermarcoen I'm happy you were able to solve the issue. 

Do you mind to share your thoughts about this idea? Unfortunately I have almost no feedback on it. I would appreciate if you tell me about any drawback you see in this solution. 

And if you cannot adopt this solution for your project I'd like to know more about your use case, so I can try to adapt it for more real-live usages.

Thank you

**Comment by petermarcoen** [comment]
@zaverden no problem anymore for this particular issue, I just changed the line endings and then it worked

**Comment by Misiu** [comment]
@petermarcoen thank you :)
I had the exact same problem.
